name: NOGAN
n_gpu: 1

data_loader:
  type: CustomDataset
  args:
    data_dir: data/
    batch_size: 1
    shuffle: False
    validation_split: 0
    num_workers: 4

model:
  type: ResNetGenerator
  args:
    input_nc: 3
    output_nc: 3

loss:
  content: perceptual_loss

metrics: [
    PSNR
]

optimizer:
  type: Adam
  args:
    lr: 0.0001
    betas: [
        0.5,
        0.999
    ]
    weight_decay: 0
    amsgrad: True

lr_scheduler:
  type: LambdaLR
  args:
    lr_lambda: origin_lr_scheduler

trainer:
  epochs: 300
  save_dir: saved/
  save_period: 5
  verbosity: 2
  monitor: max PSNR
  tensorboardX: True
  log_dir: saved/runs

others:
  content_loss_lambda: 100
